import { Injectable } from "@angular/core";
import {
  HttpRequest,
  HttpResponse,
  HttpHandler,
  HttpEvent,
  HttpInterceptor,
  HTTP_INTERCEPTORS,
} from "@angular/common/http";
import { Observable, of, throwError } from "rxjs";
import { delay, materialize, dematerialize } from "rxjs/operators";

const usersKey = "angular-14-registration-login-example-users";
let users: any[] = [
  {
    username: "admin",
    password: "admin",
    id: 1,
    firstName: "Tommy",
    lastName: "Krisna",
    email: "tommykpwork@gmail.com",
    birthDate: "2022-03-25",
    basicSalary: 35000000,
    status: "active",
    group: "Apple",
    description: "2022-03-25",
  },
  {
    username: "admin2",
    password: "admin2",
    id: 2,
    firstName: "Tommy2",
    lastName: "Krisna2",
    email: "tommykpwork2@gmail.com",
    birthDate: "2022-03-30",
    basicSalary: 5000000,
    status: "active",
    group: "Microsoft",
    description: "2022-03-30",
  },
  {
    username: "Macon Talley",
    password: "Pakistan",
    id: 3,
    firstName: "India Andrews",
    lastName: "Terry",
    email: "nunc.pulvinar@aol.couk",
    birthDate: "2022-12-9",
    basicSalary: 1772558,
    status: "active",
    group: "Twitter",
    description: "2023-04-15",
  },
  {
    username: "Carson Kidd",
    password: "Italy",
    id: 4,
    firstName: "Madonna Scott",
    lastName: "Richard",
    email: "ante@google.net",
    birthDate: "2022-08-24",
    basicSalary: 2606556,
    status: "active",
    group: "Tesla",
    description: "2024-03-14",
  },
  {
    username: "Tobias Austin",
    password: "Germany",
    id: 5,
    firstName: "Hollee Witt",
    lastName: "Hyde",
    email: "turpis.egestas@yahoo.ca",
    birthDate: "2023-12-24",
    basicSalary: 2257536,
    status: "active",
    group: "Microsoft",
    description: "2022-08-6",
  },
  {
    username: "Odessa Bullock",
    password: "Vietnam",
    id: 6,
    firstName: "Carson Conner",
    lastName: "Atkinson",
    email: "mauris.nulla@aol.net",
    birthDate: "2023-08-29",
    basicSalary: 4554143,
    status: "active",
    group: "Apple",
    description: "2023-07-22",
  },
  {
    username: "Nolan Rodgers",
    password: "Sweden",
    id: 7,
    firstName: "Briar Chandler",
    lastName: "Ross",
    email: "purus.accumsan@yahoo.org",
    birthDate: "2023-01-15",
    basicSalary: 3900399,
    status: "active",
    group: "Cognizant",
    description: "2024-03-30",
  },
  {
    username: "Hiroko Keller",
    password: "Brazil",
    id: 8,
    firstName: "Kirsten Gay",
    lastName: "Patrick",
    email: "nascetur@outlook.couk",
    birthDate: "2024-02-9",
    basicSalary: 2420369,
    status: "active",
    group: "Twitter",
    description: "2023-09-17",
  },
  {
    username: "Basil Bonner",
    password: "Australia",
    id: 9,
    firstName: "Leslie Barker",
    lastName: "Cardenas",
    email: "pellentesque@google.com",
    birthDate: "2024-05-7",
    basicSalary: 4305479,
    status: "active",
    group: "Tesla",
    description: "2023-05-6",
  },
  {
    username: "Cailin Huffman",
    password: "Peru",
    id: 10,
    firstName: "Olga Mejia",
    lastName: "Solis",
    email: "purus.sapien.gravida@icloud.edu",
    birthDate: "2023-07-24",
    basicSalary: 3186254,
    status: "active",
    group: "Microsoft",
    description: "2023-05-31",
  },
  {
    username: "Mira Merrill",
    password: "Canada",
    id: 11,
    firstName: "Jackson Mcpherson",
    lastName: "Booth",
    email: "suspendisse.eleifend.cras@outlook.edu",
    birthDate: "2022-11-5",
    basicSalary: 2560112,
    status: "active",
    group: "Apple",
    description: "2023-08-3",
  },
  {
    username: "Steel Wiley",
    password: "South Africa",
    id: 12,
    firstName: "Linus Combs",
    lastName: "Campos",
    email: "orci.quis.lectus@outlook.couk",
    birthDate: "2022-06-19",
    basicSalary: 4908973,
    status: "active",
    group: "Cognizant",
    description: "2023-02-24",
  },
  {
    username: "Basil Bonner",
    password: "Australia",
    id: 13,
    firstName: "Leslie Barker",
    lastName: "Cardenas",
    email: "pellentesque@google.com",
    birthDate: "2024-05-7",
    basicSalary: 4305479,
    status: "active",
    group: "Tesla",
    description: "2023-05-6",
  },
  {
    username: "Cailin Huffman",
    password: "Peru",
    id: 14,
    firstName: "Olga Mejia",
    lastName: "Solis",
    email: "purus.sapien.gravida@icloud.edu",
    birthDate: "2023-07-24",
    basicSalary: 3186254,
    status: "active",
    group: "Microsoft",
    description: "2023-05-31",
  },
  {
    username: "Mira Merrill",
    password: "Canada",
    id: 15,
    firstName: "Jackson Mcpherson",
    lastName: "Booth",
    email: "suspendisse.eleifend.cras@outlook.edu",
    birthDate: "2022-11-5",
    basicSalary: 2560112,
    status: "active",
    group: "Apple",
    description: "2023-08-3",
  },
  {
    username: "Steel Wiley",
    password: "South Africa",
    id: 16,
    firstName: "Linus Combs",
    lastName: "Campos",
    email: "orci.quis.lectus@outlook.couk",
    birthDate: "2022-06-19",
    basicSalary: 4908973,
    status: "active",
    group: "Cognizant",
    description: "2023-02-24",
  },
  {
    username: "Hiroko Keller",
    password: "Brazil",
    id: 17,
    firstName: "Kirsten Gay",
    lastName: "Patrick",
    email: "nascetur@outlook.couk",
    birthDate: "2024-02-9",
    basicSalary: 2420369,
    status: "active",
    group: "Twitter",
    description: "2023-09-17",
  },
  {
    username: "Basil Bonner",
    password: "Australia",
    id: 18,
    firstName: "Leslie Barker",
    lastName: "Cardenas",
    email: "pellentesque@google.com",
    birthDate: "2024-05-7",
    basicSalary: 4305479,
    status: "active",
    group: "Tesla",
    description: "2023-05-6",
  },
  {
    username: "Cailin Huffman",
    password: "Peru",
    id: 19,
    firstName: "Olga Mejia",
    lastName: "Solis",
    email: "purus.sapien.gravida@icloud.edu",
    birthDate: "2023-07-24",
    basicSalary: 3186254,
    status: "active",
    group: "Microsoft",
    description: "2023-05-31",
  },
  {
    username: "Mira Merrill",
    password: "Canada",
    id: 20,
    firstName: "Jackson Mcpherson",
    lastName: "Booth",
    email: "suspendisse.eleifend.cras@outlook.edu",
    birthDate: "2022-11-5",
    basicSalary: 2560112,
    status: "active",
    group: "Apple",
    description: "2023-08-3",
  },
  {
    username: "Steel Wiley",
    password: "South Africa",
    id: 21,
    firstName: "Linus Combs",
    lastName: "Campos",
    email: "orci.quis.lectus@outlook.couk",
    birthDate: "2022-06-19",
    basicSalary: 4908973,
    status: "active",
    group: "Cognizant",
    description: "2023-02-24",
  },
  {
    username: "Hiroko Keller",
    password: "Brazil",
    id: 22,
    firstName: "Kirsten Gay",
    lastName: "Patrick",
    email: "nascetur@outlook.couk",
    birthDate: "2024-02-9",
    basicSalary: 2420369,
    status: "active",
    group: "Twitter",
    description: "2023-09-17",
  },
  {
    username: "Basil Bonner",
    password: "Australia",
    id: 23,
    firstName: "Leslie Barker",
    lastName: "Cardenas",
    email: "pellentesque@google.com",
    birthDate: "2024-05-7",
    basicSalary: 4305479,
    status: "active",
    group: "Tesla",
    description: "2023-05-6",
  },
  {
    username: "Cailin Huffman",
    password: "Peru",
    id: 24,
    firstName: "Olga Mejia",
    lastName: "Solis",
    email: "purus.sapien.gravida@icloud.edu",
    birthDate: "2023-07-24",
    basicSalary: 3186254,
    status: "active",
    group: "Microsoft",
    description: "2023-05-31",
  },
  {
    username: "Mira Merrill",
    password: "Canada",
    id: 25,
    firstName: "Jackson Mcpherson",
    lastName: "Booth",
    email: "suspendisse.eleifend.cras@outlook.edu",
    birthDate: "2022-11-5",
    basicSalary: 2560112,
    status: "active",
    group: "Apple",
    description: "2023-08-3",
  },
  {
    username: "Steel Wiley",
    password: "South Africa",
    id: 26,
    firstName: "Linus Combs",
    lastName: "Campos",
    email: "orci.quis.lectus@outlook.couk",
    birthDate: "2022-06-19",
    basicSalary: 4908973,
    status: "active",
    group: "Cognizant",
    description: "2023-02-24",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 27,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 28,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 29,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 30,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 31,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 32,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 33,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 34,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 35,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 36,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 37,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 38,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 39,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 40,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 41,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 42,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 43,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 44,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 45,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 46,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 47,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 48,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 49,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 50,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 51,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 52,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 53,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 54,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 55,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 56,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 57,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 58,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 59,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 60,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 61,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 62,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 63,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 64,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 65,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 66,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 67,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 68,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 69,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 70,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 71,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 72,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 73,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 74,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 75,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 76,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 77,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 78,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 79,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 80,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 81,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 82,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 83,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 84,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 85,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 86,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 87,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 88,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 89,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 90,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 91,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 92,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 93,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 94,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 95,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 96,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
  {
    username: "Aimee Banks",
    password: "Russian Federation",
    id: 97,
    firstName: "Ina Houston",
    lastName: "Noble",
    email: "tellus.id@aol.ca",
    birthDate: "2022-10-2",
    basicSalary: 1048361,
    status: "active",
    group: "Twitter",
    description: "2023-10-22",
  },
  {
    username: "Bradley Kelly",
    password: "Germany",
    id: 98,
    firstName: "Herrod Gonzales",
    lastName: "Peterson",
    email: "et@outlook.edu",
    birthDate: "2023-11-17",
    basicSalary: 3533572,
    status: "active",
    group: "Tesla",
    description: "2022-07-31",
  },
  {
    username: "Alec Savage",
    password: "Costa Rica",
    id: 99,
    firstName: "Kalia Trevino",
    lastName: "Roberson",
    email: "nunc.mauris@aol.com",
    birthDate: "2023-06-4",
    basicSalary: 3045760,
    status: "active",
    group: "Microsoft",
    description: "2023-09-15",
  },
  {
    username: "Otto Nichols",
    password: "Turkey",
    id: 100,
    firstName: "Dylan Franklin",
    lastName: "Underwood",
    email: "dictum.augue.malesuada@icloud.org",
    birthDate: "2022-09-9",
    basicSalary: 4862402,
    status: "active",
    group: "Apple",
    description: "2023-06-17",
  },
  {
    username: "Vernon Avila",
    password: "Turkey",
    id: 101,
    firstName: "Dorian Roberson",
    lastName: "Buchanan",
    email: "consectetuer.ipsum.nunc@protonmail.ca",
    birthDate: "2024-04-8",
    basicSalary: 3630640,
    status: "active",
    group: "Cognizant",
    description: "2024-02-4",
  },
];

@Injectable()
export class FakeBackendInterceptor implements HttpInterceptor {
  intercept(
    request: HttpRequest<any>,
    next: HttpHandler
  ): Observable<HttpEvent<any>> {
    const { url, method, headers, body } = request;

    return handleRoute();

    function handleRoute() {
      switch (true) {
        case url.endsWith("/users/authenticate") && method === "POST":
          return authenticate();
        case url.endsWith("/users") && method === "GET":
          return getUsers();
        case url.match(/\/users\/\d+$/) && method === "GET":
          return getUserById();
        default:
          // pass through any requests not handled above
          return next.handle(request);
      }
    }

    // route functions

    function authenticate() {
      const { username, password } = body;
      const user = users.find(
        (x) => x.username === username && x.password === password
      );
      if (!user) return error("Username or password is incorrect");
      return ok({
        ...basicDetails(user),
        token: "fake-jwt-token",
      });
    }

    function getUsers() {
      if (!isLoggedIn()) return unauthorized();
      return ok(users.map((x) => basicDetails(x)));
    }

    function getUserById() {
      if (!isLoggedIn()) return unauthorized();

      const user = users.find((x) => x.id === idFromUrl());
      return ok(basicDetails(user));
    }

    // helper functions

    function ok(body?: any) {
      return of(new HttpResponse({ status: 200, body })).pipe(delay(500)); // delay observable to simulate server api call
    }

    function error(message: string) {
      return throwError(() => ({ error: { message } })).pipe(
        materialize(),
        delay(500),
        dematerialize()
      ); // call materialize and dematerialize to ensure delay even if an error is thrown (https://github.com/Reactive-Extensions/RxJS/issues/648);
    }

    function unauthorized() {
      return throwError(() => ({
        status: 401,
        error: { message: "Unauthorized" },
      })).pipe(materialize(), delay(500), dematerialize());
    }

    function basicDetails(user: any) {
      const {
        id,
        username,
        firstName,
        lastName,
        email,
        birthDate,
        basicSalary,
        status,
        group,
        description,
      } = user;
      return {
        id,
        username,
        firstName,
        lastName,
        email,
        birthDate,
        basicSalary,
        status,
        group,
        description,
      };
    }

    function isLoggedIn() {
      return headers.get("Authorization") === "Bearer fake-jwt-token";
    }

    function idFromUrl() {
      const urlParts = url.split("/");
      return parseInt(urlParts[urlParts.length - 1]);
    }
  }
}

export const fakeBackendProvider = {
  // use fake backend in place of Http service for backend-less development
  provide: HTTP_INTERCEPTORS,
  useClass: FakeBackendInterceptor,
  multi: true,
};
